export const boards = [
  {
    id: 1,
    title: "react course level 1",
    description: "blah",
    status: "done",
    category: "react",
    priority: "medium",
  },
  {
    id: 10,
    title: "react course level 1",
    description: "blah",
    status: "done",
    category: "react",
    priority: "medium",
  },
  {
    id: 2,
    title: "react course level 2",
    description: "blah",
    status: "doing",
    category: "react",
    priority: "high",
  },
  {
    id: 3,
    title: "react course level 3",
    description: "blah",
    status: "todo",
    category: "react",
    priority: "high",
  },

  {
    id: 4,
    title: "node course level 1",
    description: "blah",
    status: "done",
    category: "node",
    priority: "low",
  },
  {
    id: 5,
    title: "node course level 2",
    description: "blah",
    status: "doing",
    category: "node",
    priority: "high",
  },
  {
    id: 6,
    title: "node course level 3",
    description: "blah",
    status: "todo",
    category: "node",
    priority: "medium",
  },
];
